### PR TITLE
Update Bicep

### PR DESCRIPTION
**Pull request by JFolberth**
Update TailspinResources.bicep
- Added Managed Identity to App Service
- Set MinTLS
- Enabled FTPS Only
- Removed unnecessary dependsOn

Address #11

### CODE REVIEW

**Comment by JFolberth** [comment]
@mpieler1 for review

**Comment by mpieler1** [comment]
adding @shuerta0193 for review

**Comment by JFolberth** [comment]
@shuerta0193 looking to close out this PR.

**Comment by JFolberth** [comment]
@shuerta0193  would like to close this PR out.

**Review by shuerta0193 — APPROVED** [review]

**Pull request merged**
